apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetops-request-service-config
  namespace: fleetops-prod
  labels:
    app.kubernetes.io/name: fleetops-request-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://$(POSTGRES_HOST):5432/request_db"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  CORS_ALLOWED_ORIGINS: "https://fleetops.website"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "3"
  AWS_REGION: "us-east-1"
  VEHICLE_SERVICE_URL: "http://fleetops-vehicle-service:8080"
  MAINTENANCE_SERVICE_URL: "http://fleetops-maintenance-service:8080"
  STEP_FUNCTIONS_STATE_MACHINE_ARN: "arn:aws:states:us-east-1:538661800892:stateMachine:fleetops-prod-request-workflow"
