apiVersion: v1
kind: Service
metadata:
  name: fleetops-vehicle-service
  namespace: fleetops-prod
  labels:
    app.kubernetes.io/name: fleetops-vehicle-service
    app.kubernetes.io/environment: prod
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fleetops-vehicle-service
    app.kubernetes.io/environment: prod
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
