# FleetOps Routes - Dev Environment Values

hostname: "dev.98.86.98.79.nip.io"

namespace:
  name: fleetops-dev
  create: false

gateway:
  name: fleetops-gateway
  namespace: fleetops-platform

routes:
  auth:
    path: /auth
    serviceName: fleetops-auth-service
    servicePort: 8080
  vehicle:
    path: /api/vehicles
    serviceName: fleetops-vehicle-service
    servicePort: 8080
  maintenance:
    path: /api/tasks
    serviceName: fleetops-maintenance-service
    servicePort: 8080
  request:
    path: /api/requests
    serviceName: fleetops-request-service
    servicePort: 8080
  frontend:
    path: /
    serviceName: fleetops-frontend
    servicePort: 80
  healthz:
    path: /healthz
    pathType: Exact
    serviceName: fleetops-frontend
    servicePort: 80

