apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetops-frontend-nginx-config
  namespace: fleetops-prod
  labels:
    app.kubernetes.io/name: fleetops-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: kubectl
data:
  default.conf: |
    server {
        listen 80;
        # ALB handles TLS — Nginx only sees HTTP internally
        server_name fleetops.website www.fleetops.website;

        root /usr/share/nginx/html;
        index index.html;

        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;

        # Pass real client IP from ALB
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Health check for ALB target group
        location /healthz {
            access_log off;
            return 200 'ok';
            add_header Content-Type text/plain;
        }

        location /auth/ {
            proxy_pass http://fleetops-auth-service:8080/auth/;
        }

        location = /auth {
            proxy_pass http://fleetops-auth-service:8080/auth;
        }

        location /api/vehicles/ {
            proxy_pass http://fleetops-vehicle-service:8080/api/vehicles/;
        }

        location = /api/vehicles {
            proxy_pass http://fleetops-vehicle-service:8080/api/vehicles;
        }

        location /api/tasks/ {
            proxy_pass http://fleetops-maintenance-service:8080/api/tasks/;
        }

        location = /api/tasks {
            proxy_pass http://fleetops-maintenance-service:8080/api/tasks;
        }

        location /api/requests/ {
            proxy_pass http://fleetops-request-service:8080/api/requests/;
        }

        location = /api/requests {
            proxy_pass http://fleetops-request-service:8080/api/requests;
        }

        # React SPA — serve index.html for all other routes
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
