apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetops-postgres-config
  namespace: {{ include "fleetops-common.namespace" . }}
  labels:
    app.kubernetes.io/name: fleetops-postgres
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: "{{ .Values.config.postgresDB }}"
  DB_HOST: "fleetops-postgres"
  DB_PORT: "{{ .Values.service.port }}"
  AUTH_DB: "{{ .Values.config.authDB }}"
  VEHICLE_DB: "{{ .Values.config.vehicleDB }}"
  REQUEST_DB: "{{ .Values.config.requestDB }}"
  MAINTENANCE_DB: "{{ .Values.config.maintenanceDB }}"
