apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetops-maintenance-service-config
  namespace: {{ include "fleetops-common.namespace" . }}
  labels:
    app.kubernetes.io/name: fleetops-maintenance-service
    app.kubernetes.io/component: backend
data:
  SPRING_DATASOURCE_URL: "{{ .Values.config.datasourceUrl }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.corsAllowedOrigins }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.config.springProfilesActive }}"
