apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetops-maintenance-service-config
  namespace: {{ include "fleetops-common.namespace" . }}
  labels:
    app.kubernetes.io/name: fleetops-maintenance-service
    app.kubernetes.io/component: backend
    {{- include "fleetops-common.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "{{ .Values.config.datasourceUrl }}"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_DATABASE: "1"
  JWT_EXPIRATION: "{{ .Values.config.jwtExpiration }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.corsAllowedOrigins }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.config.springProfilesActive }}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_FLYWAY_ENABLED: "true"
  AWS_REGION: "{{ .Values.config.awsRegion }}"
  BEDROCK_REGION: "{{ .Values.config.awsRegion }}"
  BEDROCK_MODEL_ID: "{{ .Values.config.bedrockModelId }}"
