apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fleetops-app-secret
  namespace: fleetops-prod
spec:
  encryptedData:
    JWT_SECRET: AgBdymWbV/Yo4heGEfvPk3NkAdjJzs39XADWj/cPCG6OPUvA+O1moc+EboFVDDynH9zTfcP+z4iJZ105uAxSjaNMgVOhKlD5jXSWXKOTBI31TTZZm/Jl4Vjlx3OlcKD11p4XNPDHl+Q5KM9olE25nSdTKEcRU7rhntIhW7XSyv5XZgDYv2myyyBiOgZ/h5ziyyImPhYgqXF7Zf/Stkyvi6S8VL5bjtMWDCwxwzsr7X7zXdU/7DJeHFp991TFeMGIUyRVgXbOQOWE3f8d0oCOG/VrejXWXQbOL890cwATSph7eOAWiWIPZod2eVtnxfF+vGE2JoQQ/VJ/zjlUWoGF5lvITWfkSLUUG9ESBT9l+vApJH0Y7YhMVHLdhEdiaBuL4cNuIp32naDw6o8ZqIiWBNHI0M4GH35/24OJuyY3NXW2gIMRD33/GL9z4JVi+ideuzI+wPcg+i3AFNnIkz8xgm8lixBiB9ouAkgf2QQ3lP5tLQCld5+LPOL51pZqWyxLZSnSqUP/QeXNogJicNp3rezlX741V51ppFWGxe1rO5xnVYvj79rOaI+pApkfy7vZpQ5L/skSgfAx1R/xiafmC4yF8Uyj+DsksOU52SypG2jsOWuOEB1xRKBrBghl1jZnWq9k6P2mGIpLJ9xlFSZJtZu0F67HOz6OSR+OK/XvAAFlMRmD1osF36BVQaA2ftls8y3+Dokf6fuOYyyRhsOgn/RYDLOn1EkWdaC51ud2ptp4L+mz0OE=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: fleetops-secrets-prod:/Secret:fleetops-prod/fleetops-app-secret
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: security
        app.kubernetes.io/environment: prod
        app.kubernetes.io/name: fleetops-app-secret
      name: fleetops-app-secret
      namespace: fleetops-prod
    type: Opaque
---