apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fleetops-app-secret
  namespace: fleetops-dev
spec:
  encryptedData:
    JWT_SECRET: AgBU2QcAzh8g/zjqXMRoLXI8UwisxdqnlKtmAD0BF8mQuplmdTrwtjCFDppmH0g/R2nexJ4aoxwYtMTziyBz3RcTyDrbo6IrJlQmM9z8RgY6dCua9PWnG/RspZtEYT2vV9jo6+0dgouvLJ2EcmW/6RSwyT1bRvMhIaHiu21lWx1OLOWw79sW3Tyov9Zo7Cb9X1Cdigusg9U/wzFJA2z+04usKRPPlAeaCCuiqntMH3G5chv/4wvun74wODGwOyoqLklOL5gO+tUzzlX/Wrj76JcHcQT4YxvXOeyNwCMslXibVx+2JvbMv5HYfxpiat15cJ115mHZD28MKiwgnWO2Y/gpp+MzYLrQ85OrjyXx7uoaa+JhPg8crIoqj8S+fuDc+G3HBxY1bsTcYfge9vy5eVjgr4iYm2+Oa8DAWWT8Y2IuMyOo2mVcP+lIzjEN2yJJqQkrYa++RQI3rdx8uNPrz15p4MYTiXk71+OqsOjDgnIerAmvYlMV5rENLYReMsHWdB+t8x6R5kMdvdHp+dgaN+dgknOUCPIjeKKyvBIXXr7suX7cnHZ42dQ3wjk83Q7DJLrTgeT9Jk4Qx1AZHNrSyaXXe1Ku3441b+J8UjYNWHCfjWcHBf90em/RTXsFGsACITjM+NvKhd1ZCsgiUfaR+WGKefbvONtqM57HzbLiDf8Ex97D4jc02fzAIo/uD2C6QrD1vbqQMt/+sPO0BQFXLbntWdZ5nLplKSJYPjonVfGK6USSMg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: fleetops-secrets-dev:/Secret:fleetops-dev/fleetops-app-secret
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: security
        app.kubernetes.io/environment: dev
        app.kubernetes.io/name: fleetops-app-secret
      name: fleetops-app-secret
      namespace: fleetops-dev
    type: Opaque
---