apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fleetops-postgres-secret
  namespace: fleetops-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAleul/Ie2YJFnyNLrBsU3t8U5xkXbyaraMy4h1nBAbCpriiLDLyr3MFMO4+pO9AcwBIdYNgYEQCyQzAGi3ILlf3kKvxJco0cN9iQ0ObnWohbRUAVVaDx4fNVaEQaIqrxwpNMY4a/FxngiHPsKF504z8v9DJu75TgTFgZh8HNpkA9pRK4tyLZoqPnMkFZdwMY1V6acvRx2Y46L+AAK7ZopQLepno4UkXimKr3JnSNN2JjIkkVgtI8NGsVK7aFwLE66VpCmZ5ivk4SYJMqYUVE/8fkowBh3HBTP9zxndGNVT5ieDLfvPmNlGz3lx7kx58GDbIG4tfL+Iw0vBXRdkEeeRgEsNWA27biFUM9fbRUAZhjHyBUTtbg66FL1X09NXBbYBMqjROkTKVClgBlMcf+Rlhb1TTCpTSLfPsUdPHo4pQl75qyMod5Ye1QJJ8xMW++inHRy36XZ3g/pY3Vx9vJZTyg6OHUgwJSRQTTwbdL10+072n6wCAxBKLUaheLp3ve1EyMNMFof/bO/JWUUW+MNH/muia079nrg7MAVbyWidXvR9HBzWpcuZhy23wzE/7CsHCe9EKaZiFTOEsNZNHGsJ4rg+n/Ufb3DeUvzaxAC5k4aeKy3z5bdFJrB/dhCze2yQbZON/+PLlVO5u6jXjt/XG+KXPwz9iegEjge0cuYUk6ojCglKcn8tDspUmpX0MdeQsb2+1lMd4w==
    POSTGRES_USER: AgBPhOSCHyWT710vJyssuQHDRmH/xfwhi/7wzhRlZoTE5cMJIjkKUdTi/qmiSFyYlHFJPgUjv2pGNkO5YOS5JQ9xg+WnDun7Hvik3kvknp1BuVtwVPU17NfJDRlALgkAdWn+l3a4ykeTFbWDuNbh+BePirTEt1ZAoLz+Lqc2LdJqVohk+0ZY/Vh1CxLYOrevKEDMdOs7BCBeezhYgmgseWQ3OmH+BB02mHf+nstkSwcgH3WtFykxHe56+j/LEJ5S95SlnPWoWbhgXHZMIBxwewO31lrETTnCYRcbkJLpKvl+I1aR7OBRMieaA5aXpSGaAPGaZkMNUusRjI7M6VFAi4YPGMju7V1RekQNoAgTFoeDznIhlD0057xkbPXdeBj+gtCST1hmYfUOmKM/PSIOK9x5tymKSZ+Kk73+dMhL2arALrUJe9g4QeuE+21dvepevzRdZmDQapU7rceSAVxPeIaAc+dDoyuEjRM8YMciB8UbyVPRGGmOSBZunhuBWIIU33Fbidu9Dthyt4I32nBgIoZ97THh3tOW0ySmrUymqZ8jY1PJFAaeMcNVzr/Xo0ujc2trJEZF1eua6hRzk9ADrIn6wlhPXQsH48jVTJ13Knqgw2LCEcefL2T1YOnCkIAvvTX95v6d6xrRGevyHZrRGYO5we017XLKqtTHmFOvregnjBqpiO2IQlGElnKYDkG8DGYGibIM2I2kPg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: fleetops-secrets-prod:/Secret:fleetops-prod/fleetops-postgres-secret
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/environment: prod
        app.kubernetes.io/name: fleetops-postgres
      name: fleetops-postgres-secret
      namespace: fleetops-prod
    type: Opaque
---