apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fleetops-postgres-secret
  namespace: fleetops-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAg1XiNHLMvtnDFVWVq49aL4Pa8fYcq6ac1tFYqYyfV0kOVd+FP1I2c6E2RH8bRo+KnMyYQDZWJhsc1rig88KQfYT5aoK7shZjvAurY3mzU39h4n9TZJRwBHOqM/BsGllWA/KGGufEMzIkQMDbiQPZnSqH1aXg8y+2jLzxWDZkp/Li6PNjWcrZ8ZOtZc3iPd3zfKFvHDnYN9g8+tYO7szZPrZKAlN3/2Z2pUMr2ZDVEG3KafdCDLI4daUqIA+W2ke3ny6QzXkNSOv9lfosuqXN60KWxlNLmp0FWhbXl/IK4hNQLgmL92D1FnThwy3dZAoWh9HFROfTfPamYaKT+OwtgVwbOvlRAYbvMVZ5K2vvG1IHLf0MCR7GJWLbgIexWqGrnd5A025ZyLyYGtAvNjOJm0LBgc8JYXt4hd99HJbqr1YpR+31f7q+nQ0+eXRt+SOGzX+hVhdPVpseWA/Rl+4RE4p2YFA1MNTl/5f9VXbH+a62hzN7BjvE5/dsjx0+yLrdPE4eOGMqymQdAQ7VzXNaq/s739nSZl08jvMvtYLOpUXKdnuZhP40auPE6u1LV5vjvpLOCv9BrtqNivdFXM5aKKb6rafxvZobrIRRkwj+C69EjE7ke08Y9o72ZVH2pRaBL94NUBJMutW0h8qFMxL8PaumgDzQaTrZyROUZ9y2TSob773GaktvZ93pGESDQwHGfobUXHEJb7A==
    POSTGRES_USER: AgCFfHlIxNZ9HYekqnZqfEt6Rvs4nROBeTUztahXhDDI0umEbifdWZNtq2E7UXeHH3JTH9J6hjKwV3ly/qcgw/cLVxexCAqwhStemByseuggn0Itj+sp737kOBR3vF4MhJtTuVKZdYClMW6GCeIgsjoTFY+y4vgsZMWBwIAFNU5fKba2TSf2DpTA7Hn4oHjW0NZcpjlosQO+Gj0sD8HfXCvdFTAbRCtUURyJGPai+GUjgW9Bh+xwQeNB3xxsWQoe0dBXNC74RsYv26KZqjCj3m6/AQ1VfK/68fSZM6nDj5lreGL33a3HWOaM7gIN5azgDQLn2Ux9MuHn5Twmg0RTDMRltiYnLNeyLT8EzYpPFIroPqsQ0eU/lNcDF7AWT5P6Zg2ebE3jl2sqiw92DgVhAYZGGZ7tKmaKoJd6a77tHT7F0FEDCkbCkJ/mcg8mHUBI5tomQWmDzpurKiuTuZF/gzKPUmbiNJCsHqEGCpsUknpKNaXSxaWSThgk7EqC3vG8dJeUnzNf2t84FwqUUFji+3aCozwV6OJak9M/4Xk1mu3qPxRO3gt6LW0vVP6Lok3fPoaTkoHQajAgBHLYEpOvR0V7BUqFxcaQvlc1kOLbZb6VgXDCIkaZTfNq2DRjUBMh8zRKqCAclRNdByi9GpvYq3rINv1ubnzw9aivvTdI7uqjoh588NX8twCPl4DigKux7od1O04PaZBPYQ==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: fleetops-secrets-dev:/Secret:fleetops-dev/fleetops-postgres-secret
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/environment: dev
        app.kubernetes.io/name: fleetops-postgres
      name: fleetops-postgres-secret
      namespace: fleetops-dev
    type: Opaque
---