apiVersion: v1
kind: Secret
metadata:
  name: fleetops-app-secret
  namespace: fleetops-dev
  labels:
    app.kubernetes.io/name: fleetops-app-secret
    app.kubernetes.io/environment: dev
    app.kubernetes.io/component: security
type: Opaque
data:
  JWT_SECRET: Y2hhbmdlLW1lLWRldi1qd3Qtc2VjcmV0LXRvLXJlcGxhY2U=
