apiVersion: v1
kind: Service
metadata:
  name: fleetops-redis
  namespace: fleetops-dev
  labels:
    app.kubernetes.io/name: fleetops-redis
    app.kubernetes.io/environment: dev
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fleetops-redis
    app.kubernetes.io/environment: dev
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
