image:
  tag: v1.3.0 # CI/CD will update this with semver tag on first main push
replicas: 2
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
config:
  s3BucketName: "fleetops-prod-vehicle-docs"
