apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleetops-frontend-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: fleetops-frontend
    app.kubernetes.io/environment: dev
    app.kubernetes.io/component: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/johann2003/fleetops-deployments.git
    targetRevision: HEAD
    path: charts/frontend
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fleetops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
