apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleetops-secrets-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: fleetops-secrets-dev
    app.kubernetes.io/environment: dev
    app.kubernetes.io/component: security
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/FleetOps-Project-Devops/fleetops-deployments.git
    targetRevision: HEAD
    path: k8s/dev/database
  destination:
    server: https://kubernetes.default.svc
    namespace: fleetops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
