apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleetops-ingress
  namespace: fleetops-prod
  labels:
    app.kubernetes.io/name: fleetops-ingress
    app.kubernetes.io/component: networking
    app.kubernetes.io/managed-by: argocd
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certArn | quote }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.albSgId | quote }}
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: fleetops-auth-service
                port:
                  number: 8080
          - path: /api/vehicles
            pathType: Prefix
            backend:
              service:
                name: fleetops-vehicle-service
                port:
                  number: 8080
          - path: /api/tasks
            pathType: Prefix
            backend:
              service:
                name: fleetops-maintenance-service
                port:
                  number: 8080
          - path: /api/requests
            pathType: Prefix
            backend:
              service:
                name: fleetops-request-service
                port:
                  number: 8080
          - path: /api/tracking
            pathType: Prefix
            backend:
              service:
                name: fleetops-vehicle-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleetops-frontend
                port:
                  number: 80
