apiVersion: v1
kind: Secret
metadata:
  name: fleetops-app-secret
  namespace: fleetops-prod
  labels:
    app.kubernetes.io/name: fleetops-app-secret
    app.kubernetes.io/environment: prod
    app.kubernetes.io/component: security
type: Opaque
data:
  JWT_SECRET: Y2hhbmdlLW1lLXByb2Qtand0LXNlY3JldC10by1yZXBsYWNl
