apiVersion: v1
kind: Service
metadata:
  name: fleetops-postgres
  namespace: fleetops-prod
  labels:
    app.kubernetes.io/name: fleetops-postgres
    app.kubernetes.io/environment: prod
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fleetops-postgres
    app.kubernetes.io/environment: prod
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
