apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetops-postgres-config
  namespace: fleetops-prod
  labels:
    app.kubernetes.io/name: fleetops-postgres
    app.kubernetes.io/environment: prod
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: postgres
  DB_HOST: fleetops-postgres
  DB_PORT: "5432"
  AUTH_DB: auth_db
  VEHICLE_DB: vehicle_db
  REQUEST_DB: request_db
  MAINTENANCE_DB: maintenance_db
