apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleetops-routes-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: fleetops-routes
    app.kubernetes.io/environment: prod
    app.kubernetes.io/component: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/FleetOps-Project-Devops/fleetops-deployments.git
    targetRevision: HEAD
    path: charts/routes
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fleetops-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
