apiVersion: v1
kind: Service
metadata:
  name: fleetops-request-service
  namespace: {{ include "fleetops-common.namespace" . }}
  labels:
    app.kubernetes.io/name: fleetops-request-service
    app.kubernetes.io/component: backend
    {{- include "fleetops-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "fleetops-common.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
