apiVersion: v2
name: postgres
description: FleetOps PostgreSQL Database
type: application
version: 1.0.0
appVersion: "15-alpine"
dependencies:
  - name: fleetops-common
    version: "1.0.0"
    repository: file://../common
