apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetops-auth-service-config
  namespace: fleetops-prod
  labels:
    app.kubernetes.io/name: fleetops-auth-service
    app.kubernetes.io/environment: prod
    app.kubernetes.io/component: backend
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://fleetops-postgres:5432/auth_db"
  JWT_EXPIRATION: "86400000"
  CORS_ALLOWED_ORIGINS: "https://prod.98.86.98.79.nip.io"
  SPRING_PROFILES_ACTIVE: "prod"
