apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fleetops-{{ .Values.namespace.name }}-routes
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: fleetops-routes
    app.kubernetes.io/environment: {{ .Values.namespace.name }}
    app.kubernetes.io/component: gateway
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - "{{ .Values.hostname }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.auth.path }}
      backendRefs:
        - name: {{ .Values.routes.auth.serviceName }}
          port: {{ .Values.routes.auth.servicePort }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.vehicle.path }}
      backendRefs:
        - name: {{ .Values.routes.vehicle.serviceName }}
          port: {{ .Values.routes.vehicle.servicePort }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.maintenance.path }}
      backendRefs:
        - name: {{ .Values.routes.maintenance.serviceName }}
          port: {{ .Values.routes.maintenance.servicePort }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.request.path }}
      backendRefs:
        - name: {{ .Values.routes.request.serviceName }}
          port: {{ .Values.routes.request.servicePort }}
    - matches:
        - path:
            type: {{ .Values.routes.healthz.pathType | default "PathPrefix" }}
            value: {{ .Values.routes.healthz.path }}
      backendRefs:
        - name: {{ .Values.routes.healthz.serviceName }}
          port: {{ .Values.routes.healthz.servicePort }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.frontend.path }}
      backendRefs:
        - name: {{ .Values.routes.frontend.serviceName }}
          port: {{ .Values.routes.frontend.servicePort }}
    {{- if .Values.routes.grafana }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.grafana.path }}
      backendRefs:
        - name: {{ .Values.routes.grafana.serviceName }}
          namespace: {{ .Values.routes.grafana.namespace }}
          port: {{ .Values.routes.grafana.servicePort }}
    {{- end }}
