apiVersion: v1
kind: Namespace
metadata:
  name: fleetops-platform
  labels:
    app.kubernetes.io/name: fleetops-platform
    app.kubernetes.io/environment: platform
    app.kubernetes.io/component: namespace
