apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleetops-app
  namespace: fleetops-prod
  annotations:
    # Replace with actual ARN from: terraform output app_irsa_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::538661800892:role/fleetops-prod-app-irsa-role
  labels:
    app.kubernetes.io/name: fleetops-app
    app.kubernetes.io/component: security
    app.kubernetes.io/managed-by: kubectl
