apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleetops-postgres-pvc
  namespace: fleetops-prod
  labels:
    app.kubernetes.io/name: fleetops-postgres
    app.kubernetes.io/environment: prod
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fleetops-nfs
  selector:
    matchLabels:
      app.kubernetes.io/name: fleetops-postgres
      app.kubernetes.io/environment: prod
      app.kubernetes.io/component: storage
