apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetops-postgres-pv-dev
  labels:
    app.kubernetes.io/name: fleetops-postgres
    app.kubernetes.io/environment: dev
    app.kubernetes.io/component: storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fleetops-nfs
  nfs:
    server: NFS_SERVER_IP
    path: /exports/fleetops/dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleetops-postgres-pv-prod
  labels:
    app.kubernetes.io/name: fleetops-postgres
    app.kubernetes.io/environment: prod
    app.kubernetes.io/component: storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fleetops-nfs
  nfs:
    server: NFS_SERVER_IP
    path: /exports/fleetops/prod
