apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fleetops-nfs
  labels:
    app.kubernetes.io/name: fleetops-postgres
    app.kubernetes.io/environment: shared
    app.kubernetes.io/component: storage
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
